name: Sync to Hugging Face hub

on:
  push:
    branches: [main] # Or whatever your default branch is
    paths:
      - 'rag-mini-project/**'

  # To run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://<YOUR_HF_USERNAME>:$HF_TOKEN@huggingface.co/spaces/Jayanthk2004/rag-mini-project main
